### ISSUE TITLE
Alternative authentication method

### ISSUE THREAD

**Issue by ghost** [vermiculus/sx.el#167]
Sorry, I'm not familiar with the API, this this is more of a question, than a bug: I don't use OpenID to log into Stackexchange (and at all). I use plain name-password pair. Apparently this requires some JavaScript to proceed, because neither w3m nor eww can log into Stackexchange (they don't even get to the page where I would be able to input the credentials).
Since Stackexchange authentication mechanism is hidden under multiple layers of obscurity, smoke and mirrors, I never actually got around to trying to make it work with Emacs' browsers, yet I do eventually use some of the Stackexchange sites. So, if you happen to know about an alternative authentication method, I would be interested to contribute the code to handle it. (I've looked into their API documentation and it doesn't say anything about authentication, even though it has a dedicated page, it talks "philosophy" instead of describing the API).

**Comment by phil-s** [comment]
On a related note, when I go through authentication in Firefox and approve the request, I'm redirected to http://vermiculus.github.io/sx.el/auth/auth.htm#access_token=X which tells me:

> "Good news! Authentication was successful. Your authentication token is *[BLANK SPACE HERE]* Please paste this into the prompt within Emacs now."

Because it too relies upon Javascript.

(I use NoScript, so enabling Javascript for Stack Exchange does not mean that I enabled it for the SX site as well.)

Perhaps you could add in some text to indicate that the token is also present in the URL?

**Comment by vermiculus** [comment]
> Perhaps you could add in some text to indicate that the token is also present in the URL, so that users know they can alternatively copy and paste it from there?

Sounds like a good idea -- I'll see what I can do to get that pushed as soon as I can. Seems like those who've disabled JS would know what's going on, though :) But still, you have to copy the right thing.
