### ISSUE TITLE
&nbsp; is displayed verbatim, rather than as a space

### ISSUE THREAD

**Issue by phil-s** [vermiculus/sx.el#287]
e.g.: http://stackoverflow.com/q/4987760

I'm not sure whether there are other character entities which need to be looked at?

I tried grepping the Emacs lisp source for "nbsp" to see if there's an obvious centralised function for handling such things, and didn't spot an obvious canonical function; but gnus provides `html2text.el` and `html2text-substitute` which might be a good fit?

Offhand I'm not sure which character entities StackExchange supports (or not). I do note http://meta.stackexchange.com/questions/1777/what-html-tags-are-allowed-on-stack-exchange-sites , but that doesn't mention character entities specifically.

**Comment by vermiculus** [comment]
We have a defined system for this; I'll push a patch, thanks :)

**Comment by vermiculus** [comment]
Can you give a question where this problem occurs? [According to the source](https://github.com/vermiculus/sx.el/blob/50a064f5e1ec85765ab0670cd2a04d2499f6cf65/sx-encoding.el#L53), it shouldn't be displaying at all (though it should still be a unicode non-breaking space).

**Comment by vermiculus** [comment]
I've confirmed that `sx-encoding-decode-entities` isn't being called anywhere from `sx-question-mode--insert-markdown` – @Malabarba, where would be the right place to stick that call?

I'm thinking

```lisp
(defun sx-question-mode--insert-markdown (text)
  (let ((beg (point)))
    (insert
     (with-temp-buffer
       (insert text) ; <--- here
       ...))))
```

**Comment by Malabarba** [comment]
I had run into this before as well.  
Our code is working as intended, the problem is that a few question/answers actually have things like `&nbsp;` in the markdown. So stackexchange sends us `&amp;nbsp;` in the xml, which we correctly translate to `&nbsp;` in the markdown.

The reason this works is that stackexchange processes these html elements when rendering the markdown. So I guess that's what we need to do. This should be just a matter of calling `sx-encoding-decode-entities` *again* somewhere inside `sx-question-print`.

**Comment by vermiculus** [comment]
IMO, this is an issue internal to `markdown-mode`, so I'd raise it with the maintainer of that package. This has been [discussed in chat](https://gitter.im/vermiculus/sx.el?at=553815d73222e01753a10ac9).
