### ISSUE TITLE
What color theme using in the screenshot?

### ISSUE THREAD

**Issue by laohyx** [vermiculus/sx.el#290]
Hi, when I finding a good plugin viewing StackExchange in emacs, I find such a great package!
Another thing I am interested in is what is the color theme in the screenshot?
Thank you!

![screenshot](https://github.com/vermiculus/sx.el/raw/master/list-and-question.png)

**Comment by vermiculus** [comment]
@Malabarba added that screenshot to the repo, but it looks an awful lot like Monokai. 

This isn't a real issue, though :smile: be aware that our Gitter chatroom is very suited for such questions as these :smile:

**Comment by Malabarba** [comment]
It's hard to say for sure, because my color themes change a lot. But I'm 80% certain that this one was either `monokai` or `ujelly`, so try them out and let us know.

I don't think there's much issue with using issues for questions (pun intended :)). It's not like our bug tracker has been awfully busy anyway.

**Comment by Malabarba** [comment]
Actually, now that I look at it again. That screenshot looks like it's on OSX. If that's the case then it's definitely not mine. Could it be yours @vermiculus ?

**Comment by Malabarba** [comment]
In any case, I'm sure git can tell us whose it is. :-)

**Comment by vermiculus** [comment]
@Malabarba Actually git is were I looked -- I was also pretty confident that I took it (monokai is still my theme), but it looks like you actually added it to the repo :) 

In that case, it's definitely Monokai.
