### ISSUE TITLE
Am getting emails of every issues to jochendaum

### ISSUE THREAD

**Issue by jochendaum** [vermiculus/sx.el#326]
Hi,

I never subscribed to anything, nor am I watching. How can I stop getting issues on this report emailed to me?

**Comment by vermiculus** [comment]
That's… strange. I'd reach out to github support. I'll double check settings here.

**Comment by jochendaum** [comment]
I be contacted @github on Twitter. The only thing I consciously remember doing is share the report with a friend that is an Emacs fan. thanks for looking into it.

**Comment by vermiculus** [comment]
It doesn't appear that you're [watching this repository](https://github.com/vermiculus/sx.el/watchers) which is the only thing (to my knowledge) that would explain this behavior, so I'm not sure what's going on – it's nothing on our end.

Next steps are really just to get into contact with GitHub (I've had nothing but the best luck with email support) and resolve the issue with your account.

Since it's not an issue with sx.el, I'm closing the issue, but feel free to continue the conversation here if it's convenient 😄

**Comment by agrihealth** [comment]
argh, i should have checked the email source earlier. This is delivered to a client account of mine. now unwatched
